import raw from '@/data/keyTerms.json';

/**
 * The German words worth locking onto for one question.
 *
 * The exam draws its questions verbatim from the catalogue, so passing it is a
 * recognition task: you need the few words that say which question this is and
 * which option answers it. Generated by `scripts/key-terms.mjs`.
 */
export type KeyTerms = {
  /** The stem asks which statement is false - the classic way to lose a known question. */
  trap: boolean;
  /** Rarest content words in the question stem. */
  ask: string[];
  /** Rarest content words in the correct answer; empty for picture questions. */
  answer: string[];
};

const TERMS = raw as Record<string, KeyTerms>;

export function keyTermsFor(id: number): KeyTerms | null {
  return TERMS[String(id)] ?? null;
}
