#!/usr/bin/env node
/**
 * Turns the vendored BAMF catalogue in `data-source/` into the app dataset.
 *
 *   data-source/questions.raw.json  ->  src/data/questions.json
 *   data-source/images/*.png        ->  assets/questions/*.webp
 *
 * Run with `npm run data`. Images are only regenerated when `data-source/images`
 * is present (see scripts/fetch-source.mjs) so a normal clone can still rebuild
 * the JSON without the 35 MB of originals.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { classifyTopic, pickIcon, pickIllustration, TOPICS } from './topics.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC_JSON = path.join(ROOT, 'data-source', 'questions.raw.json');
const SRC_IMAGES = path.join(ROOT, 'data-source', 'images');
const OUT_DATA = path.join(ROOT, 'src', 'data');
const OUT_IMAGES = path.join(ROOT, 'assets', 'questions');

/**
 * Upstream labels questions 431-440 as "Sachsen" but they are the
 * Sachsen-Anhalt block. Without this fix Sachsen would have 20 questions and
 * Sachsen-Anhalt none.
 */
function fixState(q) {
  if (q.type === 'state' && q.id >= 431 && q.id <= 440) return 'Sachsen-Anhalt';
  return q.state;
}

const STATE_ORDER = [
  'Baden-Württemberg', 'Bayern', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg',
  'Hessen', 'Mecklenburg-Vorpommern', 'Niedersachsen', 'Nordrhein-Westfalen',
  'Rheinland-Pfalz', 'Saarland', 'Sachsen', 'Sachsen-Anhalt',
  'Schleswig-Holstein', 'Thüringen',
];

/** Short codes + emoji flags-ish markers used in the state picker. */
const STATE_META = {
  'Baden-Württemberg': { code: 'BW', capital: 'Stuttgart' },
  'Bayern': { code: 'BY', capital: 'München' },
  'Berlin': { code: 'BE', capital: 'Berlin' },
  'Brandenburg': { code: 'BB', capital: 'Potsdam' },
  'Bremen': { code: 'HB', capital: 'Bremen' },
  'Hamburg': { code: 'HH', capital: 'Hamburg' },
  'Hessen': { code: 'HE', capital: 'Wiesbaden' },
  'Mecklenburg-Vorpommern': { code: 'MV', capital: 'Schwerin' },
  'Niedersachsen': { code: 'NI', capital: 'Hannover' },
  'Nordrhein-Westfalen': { code: 'NW', capital: 'Düsseldorf' },
  'Rheinland-Pfalz': { code: 'RP', capital: 'Mainz' },
  'Saarland': { code: 'SL', capital: 'Saarbrücken' },
  'Sachsen': { code: 'SN', capital: 'Dresden' },
  'Sachsen-Anhalt': { code: 'ST', capital: 'Magdeburg' },
  'Schleswig-Holstein': { code: 'SH', capital: 'Kiel' },
  'Thüringen': { code: 'TH', capital: 'Erfurt' },
};

async function buildImages(usedImages) {
  if (!fs.existsSync(SRC_IMAGES)) {
    console.warn('! data-source/images not found - skipping image conversion.');
    console.warn('  Run `node scripts/fetch-source.mjs` first to regenerate them.');
    return;
  }
  const { default: sharp } = await import('sharp');
  fs.rmSync(OUT_IMAGES, { recursive: true, force: true });
  fs.mkdirSync(OUT_IMAGES, { recursive: true });

  let bytes = 0;
  for (const name of usedImages) {
    const from = path.join(SRC_IMAGES, name);
    const to = path.join(OUT_IMAGES, name.replace(/\.png$/i, '.webp'));
    const buf = await sharp(from)
      .resize({ width: 512, height: 512, fit: 'inside', withoutEnlargement: true })
      .webp({ quality: 80, effort: 5 })
      .toBuffer();
    fs.writeFileSync(to, buf);
    bytes += buf.length;
  }
  console.log(`  images: ${usedImages.length} -> ${(bytes / 1024 / 1024).toFixed(2)} MB webp`);
}

/**
 * Metro cannot `require()` an asset from a runtime-built string, so the image
 * map has to be a literal module. This generates it.
 */
function writeImageMap(usedImages) {
  const entries = usedImages
    .map((name) => {
      const key = name.replace(/^images\//, '').replace(/\.png$/i, '');
      return `  '${key}': require('../../assets/questions/${key}.webp'),`;
    })
    .join('\n');

  const file = `// GENERATED by scripts/build-data.mjs - do not edit.
import type { ImageSourcePropType } from 'react-native';

export const questionImages: Record<string, ImageSourcePropType> = {
${entries}
};
`;
  fs.writeFileSync(path.join(OUT_DATA, 'questionImages.ts'), file);
}

async function main() {
  const raw = JSON.parse(fs.readFileSync(SRC_JSON, 'utf8'));
  fs.mkdirSync(OUT_DATA, { recursive: true });

  const usedImages = new Set();
  const questions = raw.map((q) => {
    const state = fixState(q);
    const topic = classifyTopic(q);
    const en = q.translations?.en ?? {};

    // Upstream uses a string for questions that show one picture, and an array
    // of four when each answer option is a picture.
    const rawImages = q.image == null ? [] : Array.isArray(q.image) ? q.image : [q.image];
    const images = rawImages.map((p) => {
      const name = p.replace(/^images\//, '');
      usedImages.add(name);
      return name.replace(/\.png$/i, '');
    });
    const imageMode = images.length === 0 ? null : images.length === 1 ? 'single' : 'options';

    return {
      id: q.id,
      kind: q.type === 'state' ? 'state' : 'general',
      state: state ?? null,
      topic,
      icon: pickIcon(q, topic),
      illustration: images.length ? null : pickIllustration(q, topic),
      images,
      imageMode,
      imageCredit: q.imageText ?? null,
      de: { text: q.text, options: q.options },
      en: { text: en.text ?? null, options: en.options ?? null },
      context: en.context ?? null,
      answer: q.correctAnswer,
    };
  });

  const byState = {};
  for (const q of questions) {
    if (q.kind === 'state' && q.state) byState[q.state] = (byState[q.state] ?? 0) + 1;
  }
  const missing = STATE_ORDER.filter((s) => byState[s] !== 10);
  if (missing.length) throw new Error(`Expected 10 questions per state, got issues for: ${missing.join(', ')}`);

  const general = questions.filter((q) => q.kind === 'general');
  if (general.length !== 300) throw new Error(`Expected 300 general questions, got ${general.length}`);

  fs.writeFileSync(path.join(OUT_DATA, 'questions.json'), JSON.stringify(questions));
  fs.writeFileSync(
    path.join(OUT_DATA, 'meta.json'),
    JSON.stringify(
      {
        topics: TOPICS,
        states: STATE_ORDER.map((name) => ({ name, ...STATE_META[name] })),
        counts: {
          total: questions.length,
          general: general.length,
          state: questions.length - general.length,
          withImages: questions.filter((q) => q.images.length).length,
        },
      },
      null,
      2,
    ),
  );

  const sorted = [...usedImages].sort();
  await buildImages(sorted);
  writeImageMap(sorted);

  const dist = {};
  for (const q of general) dist[q.topic] = (dist[q.topic] ?? 0) + 1;
  console.log(`Wrote ${questions.length} questions (${general.length} general + ${questions.length - general.length} state).`);
  console.log('  general topic split:', dist);
  console.log('  illustrations:', new Set(questions.map((q) => q.illustration).filter(Boolean)).size, 'distinct scenes');
  console.log('  without any visual:', questions.filter((q) => !q.images.length && !q.illustration).length);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
