/**
 * Everyday context for the 300 general questions.
 *
 * Each note answers "so what does this mean for me?" - the thing a question
 * paper cannot tell you. Written by hand, and deliberately limited to durable
 * facts: how something works, which office does it, what a right protects.
 * Current office-holders and current fees are left to the question text.
 */
const n = (en, de) => ({ en, de });

export const GENERAL_NOTES = {
  1: n('You can criticise the government in a pub, a newspaper or a protest and nothing happens to you. In many countries people are jailed for exactly that. This is the difference.',
       'Du darfst die Regierung in der Kneipe, in der Zeitung oder auf einer Demo kritisieren, ohne dass dir etwas passiert. In vielen Ländern kommt man dafür ins Gefängnis.'),
  2: n('Religious education is a normal school subject here, but never compulsory. Parents decide until the child is 14, then the child decides. There is always an alternative subject such as ethics.',
       'Religionsunterricht ist ein normales Schulfach, aber nie Pflicht. Bis 14 entscheiden die Eltern, danach das Kind selbst. Es gibt immer ein Ersatzfach wie Ethik.'),
  3: n('Rechtsstaat means the government is under the law too. A minister who breaks the law can be taken to court like anyone else, and you can sue a public authority and win.',
       'Rechtsstaat heißt: Auch der Staat steht unter dem Gesetz. Eine Ministerin kann vor Gericht wie jede andere, und du kannst eine Behörde verklagen und gewinnen.'),
  4: n('Basic rights sit in Articles 1 to 19 of the Grundgesetz and bind every authority directly. You do not apply for them; you already have them.',
       'Die Grundrechte stehen in Artikel 1 bis 19 des Grundgesetzes und binden jede Behörde unmittelbar. Du musst sie nicht beantragen, du hast sie bereits.'),
  5: n('Free elections mean nobody can pressure you: not an employer, not a party, not your family. That is also why the voting booth has a curtain.',
       'Freie Wahl heißt: Niemand darf dich unter Druck setzen – kein Arbeitgeber, keine Partei, keine Familie. Deshalb hat die Wahlkabine einen Vorhang.'),
  6: n('It is called Grundgesetz, not Verfassung, because in 1949 it was meant to be temporary until Germany was reunited. It stayed, and in 1990 it became the constitution for the whole country.',
       'Es heißt Grundgesetz und nicht Verfassung, weil es 1949 nur vorläufig gelten sollte, bis Deutschland wiedervereinigt ist. 1990 wurde es die Verfassung für ganz Deutschland.'),
  7: n('You may believe anything, change belief, or believe nothing. No employer or authority may require a religion, and no one may be forced into a religious ceremony.',
       'Du darfst glauben, was du willst, den Glauben wechseln oder gar nicht glauben. Kein Arbeitgeber und keine Behörde darf eine Religion verlangen.'),
  8: n('The Grundgesetz guarantees equal rights, not equal wealth. It promises a social state that cushions hardship, which is a very different promise.',
       'Das Grundgesetz garantiert gleiche Rechte, nicht gleiches Vermögen. Es verspricht einen Sozialstaat, der Not abfedert – das ist etwas anderes.'),
  9: n('Asylum is the one basic right written specifically for non-Germans, put there in 1949 by people who had themselves fled the Nazis and been turned away.',
       'Asyl ist das eine Grundrecht, das ausdrücklich für Nicht-Deutsche gilt. 1949 schrieben es Menschen hinein, die selbst vor den Nazis geflohen und abgewiesen worden waren.'),
  10: n('Germany has no death penalty and no corporal punishment. Fines and prison are the tools the state has, and even prison must respect human dignity.',
        'Deutschland hat keine Todesstrafe und keine Prügelstrafe. Geldstrafe und Freiheitsstrafe sind die Mittel des Staates – und auch die Haft muss die Menschenwürde achten.'),
  11: n('One constitution, two names in everyday speech. Officially it is the Grundgesetz, and both words appear in the exam.',
        'Eine Verfassung, zwei Namen im Alltag. Amtlich heißt sie Grundgesetz, und beide Wörter kommen im Test vor.'),
  12: n('A parliamentary majority cannot simply delete a basic right. The Bundesverfassungsgericht would strike the law down. This is the whole point of having a constitution.',
        'Eine Mehrheit im Parlament kann ein Grundrecht nicht einfach streichen. Das Bundesverfassungsgericht würde das Gesetz aufheben. Genau dafür gibt es eine Verfassung.'),
  13: n('The opposition is not a nuisance, it is part of the machinery. It questions ministers, demands documents and can call inquiries, which is how the public finds things out.',
        'Die Opposition ist kein Störfaktor, sondern Teil des Systems. Sie befragt Ministerinnen, fordert Akten und kann Untersuchungsausschüsse einsetzen.'),
  14: n('Freedom of expression covers the internet as much as the street. It protects opinions, including ones most people dislike, not deliberate lies or threats.',
        'Die Meinungsfreiheit gilt im Internet genauso wie auf der Straße. Sie schützt Meinungen, auch unbeliebte – aber keine gezielten Lügen oder Drohungen.'),
  15: n('Forced labour is banned, a direct answer to the Nazi state, which used millions of forced labourers. Only a court may order work, and only as part of a sentence.',
        'Zwangsarbeit ist verboten – eine direkte Antwort auf den NS-Staat, der Millionen Zwangsarbeiter einsetzte. Arbeit anordnen darf nur ein Gericht, und nur im Strafvollzug.'),
  16: n('Free speech ends where it becomes defamation, incitement or Holocaust denial. You can say a policy is terrible; you cannot invent crimes about a named person.',
        'Die Meinungsfreiheit endet bei Beleidigung, Volksverhetzung und Holocaustleugnung. Du darfst eine Politik schrecklich finden, aber keine Straftaten über eine Person erfinden.'),
  17: n('Discrimination by origin, sex, religion, disability or belief is illegal in housing, work and services. The AGG gives you a route to complain and to claim compensation.',
        'Diskriminierung wegen Herkunft, Geschlecht, Religion, Behinderung oder Weltanschauung ist verboten – bei Wohnung, Arbeit und Dienstleistungen. Das AGG gibt dir einen Weg zur Beschwerde.'),
  18: n('Article 1 is first on purpose: dignity before democracy, before the state. Everything else in the Grundgesetz is built on it.',
        'Artikel 1 steht mit Absicht ganz vorn: die Würde vor der Demokratie, vor dem Staat. Alles andere im Grundgesetz baut darauf auf.'),
  19: n('Freizügigkeit is why you can take a job in another city without asking permission. The only formality is registering your new address within 14 days.',
        'Freizügigkeit heißt: Du kannst in einer anderen Stadt arbeiten, ohne zu fragen. Die einzige Formalität ist die Anmeldung der neuen Adresse binnen 14 Tagen.'),
  20: n('Parties aiming to abolish democracy can be banned by the Bundesverfassungsgericht, and two have been. A democracy that cannot defend itself does not last.',
        'Parteien, die die Demokratie abschaffen wollen, kann das Bundesverfassungsgericht verbieten – zweimal ist das geschehen. Eine wehrlose Demokratie hält nicht.'),
  21: n('The federal eagle appears on passports, coins, court buildings and the Bundestag. Learning it means you can tell a federal document from a state one at a glance.',
        'Der Bundesadler ist auf Pass, Münzen, Gerichtsgebäuden und im Bundestag. Wer ihn kennt, erkennt sofort ein Bundesdokument.'),
  22: n('Republic means no king or queen and a head of state who is elected for a fixed term. Germany last had a monarch in 1918.',
        'Republik heißt: kein König, keine Königin, und ein gewähltes Staatsoberhaupt auf Zeit. Den letzten Monarchen hatte Deutschland 1918.'),
  23: n('Most people here are employees rather than self-employed, which is why so much of the system, from health insurance to pensions, is built around a payslip.',
        'Die meisten sind angestellt, nicht selbständig. Deshalb ist vieles – von der Krankenkasse bis zur Rente – um die Gehaltsabrechnung herum gebaut.'),
  24: n('Sixteen states, and which one you live in genuinely changes your life: school system, school holidays, police, shop hours, even some public holidays.',
        'Sechzehn Länder – und in welchem du wohnst, ändert wirklich etwas: Schulsystem, Ferien, Polizei, Ladenöffnung, sogar manche Feiertage.'),
  25: n('Elsass-Lothringen is in France. It was German between 1871 and 1918 and again during the war, which is why it appears here as a trap.',
        'Elsass-Lothringen liegt in Frankreich. Es war 1871 bis 1918 und erneut im Krieg deutsch – deshalb steht es hier als Falle.'),
  26: n('Four words carry the whole state: democratic, social, federal, and a Rechtsstaat. All four are protected forever by Article 79.',
        'Vier Worte tragen den ganzen Staat: demokratisch, sozial, bundesstaatlich, Rechtsstaat. Alle vier schützt Artikel 79 dauerhaft.'),
  27: n('Bundesstaat means power is shared between the federal level and the states by design, so no single centre can control everything.',
        'Bundesstaat heißt: Die Macht ist bewusst zwischen Bund und Ländern geteilt, damit keine einzige Zentrale alles kontrolliert.'),
  28: n('You elect the Bundestag directly. You do not elect the chancellor or the president directly, which surprises many newcomers.',
        'Den Bundestag wählst du direkt. Kanzlerin und Bundespräsident wählst du nicht direkt – das überrascht viele.'),
  29: n('The eagle has been a German symbol for centuries. Today it appears in a deliberately plain, friendly form, not an aggressive one.',
        'Der Adler ist seit Jahrhunderten ein deutsches Symbol. Heute zeigt er sich bewusst schlicht und freundlich, nicht aggressiv.'),
  30: n('Press censorship is explicitly forbidden. Journalists may publish things the government hates, and the government has no power to stop the presses.',
        'Zensur der Presse ist ausdrücklich verboten. Journalistinnen dürfen veröffentlichen, was der Regierung nicht passt – sie kann es nicht verhindern.'),
  31: n('No single party has won a majority alone for decades, so governments are coalitions. That is why forming one takes weeks of negotiation after an election.',
        'Seit Jahrzehnten hat keine Partei allein die Mehrheit, also regieren Koalitionen. Deshalb dauert die Regierungsbildung nach einer Wahl Wochen.'),
  32: n('The press is often called the fourth estate, but it is not state power. It is private and independent, and that independence is precisely its job.',
        'Die Presse heißt oft vierte Gewalt, ist aber keine Staatsgewalt. Sie ist privat und unabhängig – und genau das ist ihre Aufgabe.'),
  33: n('Church and state are separated, but not as strictly as in France. The state stays neutral yet still collects church tax for registered members.',
        'Kirche und Staat sind getrennt, aber nicht so streng wie in Frankreich. Der Staat bleibt neutral, zieht aber die Kirchensteuer für Mitglieder ein.'),
  34: n('There is no throne. Germany became a republic in 1918, and the Grundgesetz makes that permanent.',
        'Es gibt keinen Thron. 1918 wurde Deutschland Republik, und das Grundgesetz macht das dauerhaft.'),
  35: n('Social insurance is funded by contributions from wages, not from general taxes. That is the deduction between Brutto and Netto on your payslip.',
        'Die Sozialversicherung finanziert sich aus Beiträgen vom Lohn, nicht aus Steuern. Das ist der Abzug zwischen Brutto und Netto.'),
  36: n('Health insurance is compulsory for everyone living here. Contributions follow income rather than health risk, which is why serious illness does not bankrupt people.',
        'Die Krankenversicherung ist Pflicht für alle hier. Der Beitrag richtet sich nach dem Einkommen, nicht nach dem Risiko – deshalb ruiniert eine schwere Krankheit niemanden.'),
  37: n('Your state premier matters more than most people expect: schools, police and culture are decided at that level, not in Berlin.',
        'Die Ministerpräsidentin deines Landes ist wichtiger, als viele denken: Schule, Polizei und Kultur werden dort entschieden, nicht in Berlin.'),
  38: n('Democratic and social are not decoration. Courts have used the social state clause to require a minimum standard of living.',
        'Demokratisch und sozial sind keine Floskeln. Gerichte haben aus dem Sozialstaatsgebot ein menschenwürdiges Existenzminimum abgeleitet.'),
  39: n('Each state has its own government and parliament, so there are seventeen governments in Germany: one federal and sixteen state.',
        'Jedes Land hat eigene Regierung und eigenes Parlament. Es gibt also siebzehn Regierungen: eine im Bund, sechzehn in den Ländern.'),
  40: n('Only the third verse of the old song is the anthem. The earlier verses are not sung officially, because of how they were used before 1945.',
        'Nur die dritte Strophe ist die Hymne. Die früheren Strophen werden offiziell nicht gesungen – wegen ihrer Verwendung vor 1945.'),
  41: n('Several parties exist so that real disagreements have somewhere to go. A one-party state is the definition of what Germany is built to avoid.',
        'Mehrere Parteien gibt es, damit echter Streit einen Ort hat. Ein Einparteienstaat ist genau das, was Deutschland vermeiden soll.'),
  42: n('Parliament passes laws, not the chancellor. A government can propose whatever it likes; without a Bundestag majority nothing becomes law.',
        'Gesetze beschließt das Parlament, nicht die Kanzlerin. Eine Regierung kann vorschlagen, was sie will – ohne Mehrheit im Bundestag wird nichts daraus.'),
  43: n('Only the Bundesverfassungsgericht may ban a party, never the government. Otherwise a government could simply outlaw its opponents.',
        'Nur das Bundesverfassungsgericht darf eine Partei verbieten, nie die Regierung. Sonst könnte eine Regierung einfach ihre Gegner verbieten.'),
  44: n('You never vote for the president directly. The Bundesversammlung does that, which keeps the office above party campaigning.',
        'Den Bundespräsidenten wählst du nie direkt. Das macht die Bundesversammlung – so bleibt das Amt aus dem Wahlkampf heraus.'),
  45: n('Care insurance was added in 1995 as the fifth pillar, because people live long enough to need years of care at the end of life.',
        'Die Pflegeversicherung kam 1995 als fünfte Säule dazu, weil Menschen alt genug werden, um am Lebensende jahrelang Pflege zu brauchen.'),
  46: n('Roads, schools and courts are what your taxes buy. Infrastructure is a core state task, not an optional extra.',
        'Straßen, Schulen und Gerichte kaufst du mit deinen Steuern. Infrastruktur ist Kernaufgabe des Staates, kein Extra.'),
  47: n('The state provides a safety net, not a lifestyle. Holidays are between you and your employer, and the law sets only a minimum.',
        'Der Staat sichert ab, er finanziert keinen Lebensstil. Urlaub regelst du mit dem Arbeitgeber; das Gesetz setzt nur ein Minimum.'),
  48: n('A citizens’ assembly can advise but has no constitutional power. The constitutional organs are a fixed, short list.',
        'Eine Bürgerversammlung kann beraten, hat aber keine Verfassungsmacht. Die Verfassungsorgane sind eine feste, kurze Liste.'),
  49: n('School policy is the clearest example of federalism. Move states with school-age children and you may meet a different system entirely.',
        'Schulpolitik ist das klarste Beispiel für Föderalismus. Wer mit Schulkindern das Land wechselt, trifft oft auf ein ganz anderes System.'),
  50: n('Soziale Marktwirtschaft means a free market plus rules: competition law, worker protection and social insurance are part of the design, not exceptions.',
        'Soziale Marktwirtschaft heißt: freier Markt plus Regeln. Wettbewerbsrecht, Arbeitsschutz und Sozialversicherung gehören dazu, sie sind keine Ausnahme.'),
  51: n('Only the state may use force, and only under law. Private security has no police powers and may not detain you on suspicion.',
        'Gewalt darf nur der Staat ausüben, und nur nach Gesetz. Privater Sicherheitsdienst hat keine Polizeibefugnisse und darf dich nicht einfach festhalten.'),
  52: n('All state power comes from the people. Officials, judges and ministers hold power on loan, and it can be taken back at an election.',
        'Alle Staatsgewalt geht vom Volke aus. Beamte, Richterinnen und Ministerinnen haben Macht nur geliehen – bei der Wahl kann man sie zurücknehmen.'),
  53: n('The state must obey its own laws. If an authority oversteps, you can take it to an administrative court, and people win such cases regularly.',
        'Der Staat muss seine eigenen Gesetze einhalten. Geht eine Behörde zu weit, kannst du vor das Verwaltungsgericht – und viele gewinnen dort.'),
  54: n('There are exactly three powers: legislative, executive, judicial. "Direktive" is invented, and this question is testing whether you noticed.',
        'Es gibt genau drei Gewalten: Legislative, Exekutive, Judikative. „Direktive" ist erfunden – die Frage prüft, ob du aufpasst.'),
  55: n('The Reichstag building houses the Bundestag. Its glass dome is open to the public for free, and you can look down into the chamber.',
        'Im Reichstagsgebäude tagt der Bundestag. Die Glaskuppel ist kostenlos zugänglich, und von oben schaust du in den Plenarsaal.'),
  56: n('The Ordnungsamt is the office you meet over parking, noise complaints and street permits. It is local, not federal.',
        'Das Ordnungsamt triffst du bei Parken, Lärmbeschwerden und Sondernutzung. Es ist örtlich, nicht Bundessache.'),
  57: n('The Bundestag president chairs debates and keeps order, and by tradition comes from the largest parliamentary group.',
        'Die Bundestagspräsidentin leitet die Debatten und sorgt für Ordnung. Traditionell kommt sie aus der stärksten Fraktion.'),
  58: n('The president formally appoints ministers, but on the chancellor’s proposal. The signature is real, the choice is not.',
        'Der Bundespräsident ernennt die Ministerinnen formal, aber auf Vorschlag der Kanzlerin. Die Unterschrift ist echt, die Auswahl nicht.'),
  59: n('Jewish life on German soil is documented from around 321 CE in Cologne, so roughly 1,700 years, far older than Germany itself.',
        'Jüdisches Leben auf deutschem Boden ist ab etwa 321 in Köln belegt – rund 1.700 Jahre, viel älter als Deutschland selbst.'),
  60: n('The legislature is both chambers together: Bundestag and Bundesrat. Laws affecting the states need both.',
        'Die Legislative sind beide Kammern: Bundestag und Bundesrat. Gesetze, die die Länder betreffen, brauchen beide.'),
  61: n('Same principle, asked twice in the catalogue: power belongs to the people. Expect this idea in several wordings on the day.',
        'Dasselbe Prinzip, im Katalog zweimal gefragt: Die Macht gehört dem Volk. Rechne mit mehreren Formulierungen.'),
  62: n('A Landtagswahl elects your state parliament. Turnout is usually lower than for federal elections, even though it decides schools and police.',
        'Die Landtagswahl wählt dein Landesparlament. Die Beteiligung ist meist niedriger als im Bund – obwohl es um Schule und Polizei geht.'),
  63: n('Courts are deliberately not part of the executive. A judge cannot be told how to rule by any minister.',
        'Gerichte gehören bewusst nicht zur Exekutive. Keine Ministerin darf einer Richterin sagen, wie sie zu urteilen hat.'),
  64: n('Three levels: Bund, Länder, Kommunen. Most things you actually need day to day happen at the third one, in your town hall.',
        'Drei Ebenen: Bund, Länder, Kommunen. Das meiste, was du wirklich brauchst, passiert auf der dritten – im Rathaus.'),
  65: n('The Bundestag elects the chancellor, who then picks the cabinet. Parliament does not assemble the government itself.',
        'Der Bundestag wählt die Kanzlerin, die dann das Kabinett zusammenstellt. Das Parlament bildet die Regierung nicht selbst.'),
  66: n('Jewish communities were destroyed in the Holocaust and rebuilt after 1945, substantially through immigration from the former Soviet Union.',
        'Die jüdischen Gemeinden wurden im Holocaust vernichtet und nach 1945 wieder aufgebaut – wesentlich durch Zuwanderung aus der früheren Sowjetunion.'),
  67: n('Education is the states’ flagship responsibility, which is why there is no single German school system but sixteen.',
        'Bildung ist die wichtigste Länderaufgabe. Deshalb gibt es kein deutsches Schulsystem, sondern sechzehn.'),
  68: n('The state supervises all schools, including private ones, so that every child gets a real education and none is cut off from society.',
        'Der Staat beaufsichtigt alle Schulen, auch private, damit jedes Kind wirklich lernt und keines von der Gesellschaft abgeschnitten wird.'),
  69: n('The bottom tier is your Gemeinde. It runs the Bürgeramt, kindergartens, libraries and local roads, and you can attend its council meetings.',
        'Die unterste Ebene ist die Gemeinde. Sie betreibt Bürgeramt, Kitas, Büchereien und Straßen – und ihre Ratssitzungen sind öffentlich.'),
  70: n('The president proposes the chancellor to the Bundestag, which then votes. In practice the proposal follows the coalition talks.',
        'Der Bundespräsident schlägt dem Bundestag die Kanzlerin vor, der dann wählt. In der Praxis folgt der Vorschlag den Koalitionsgesprächen.'),
  71: n('The chancellor works in the Bundeskanzleramt in Berlin. Schloss Meseberg is only the government guest house.',
        'Die Kanzlerin arbeitet im Bundeskanzleramt in Berlin. Schloss Meseberg ist nur das Gästehaus der Regierung.'),
  72: n('The chancellor changes; the office does not. Check who currently holds it before your test date, because the catalogue is updated.',
        'Die Person wechselt, das Amt bleibt. Prüfe vor dem Test, wer gerade im Amt ist – der Katalog wird aktualisiert.'),
  73: n('Which groups are largest shifts with every election. Always confirm the current composition close to your test date.',
        'Welche Fraktionen die größten sind, ändert sich mit jeder Wahl. Prüfe die aktuelle Zusammensetzung kurz vor dem Test.'),
  74: n('The Bundestag is the national parliament. You can watch a debate from the visitors’ gallery for free.',
        'Der Bundestag ist das Parlament für ganz Deutschland. Von der Besuchertribüne kannst du kostenlos zusehen.'),
  75: n('The president is head of state but deliberately weak: a deliberate contrast with the powerful Reichspräsident of the Weimar Republic.',
        'Der Bundespräsident ist Staatsoberhaupt, aber bewusst schwach – als Gegenentwurf zum mächtigen Reichspräsidenten der Weimarer Republik.'),
  76: n('Learning the party abbreviations makes German news usable. CDU is the large centre-right party, active everywhere except Bavaria.',
        'Wer die Parteikürzel kennt, versteht deutsche Nachrichten. Die CDU ist die große Mitte-Rechts-Partei – außer in Bayern.'),
  77: n('The Bundeswehr is a parliamentary army: the Bundestag, not the government alone, must approve deployments abroad.',
        'Die Bundeswehr ist eine Parlamentsarmee: Auslandseinsätze muss der Bundestag genehmigen, nicht die Regierung allein.'),
  78: n('The SPD is the oldest party still sitting in the Bundestag, founded in the 19th century and banned under the Nazis.',
        'Die SPD ist die älteste noch im Bundestag vertretene Partei, im 19. Jahrhundert gegründet und unter den Nazis verboten.'),
  79: n('The FDP is the small liberal party, historically often the junior partner that decided which bloc could govern.',
        'Die FDP ist die kleine liberale Partei – historisch oft der Juniorpartner, der entschied, welcher Block regieren konnte.'),
  80: n('Karlsruhe, not Berlin. The constitutional court sits away from the capital on purpose, to keep its distance from politics.',
        'Karlsruhe, nicht Berlin. Das Verfassungsgericht sitzt bewusst fern der Hauptstadt, um Abstand zur Politik zu halten.'),
  81: n('Parliament chooses the chancellor, so a government exists only as long as it keeps a majority in the Bundestag.',
        'Das Parlament wählt die Kanzlerin. Eine Regierung besteht also nur, solange sie die Mehrheit im Bundestag hat.'),
  82: n('The chancellor sets the overall policy direction, the Richtlinienkompetenz, and ministers run their departments within it.',
        'Die Kanzlerin bestimmt die Richtlinien der Politik, und die Ministerinnen führen ihre Häuser in diesem Rahmen.'),
  83: n('Asked twice in the catalogue. The answer is the Bundestag both times.',
        'Steht zweimal im Katalog. Die Antwort ist beide Male: der Bundestag.'),
  84: n('The president represents the country, signs laws and can refuse to sign one that is clearly unconstitutional. It is a check, not a throne.',
        'Der Bundespräsident repräsentiert das Land, unterschreibt Gesetze und kann die Unterschrift verweigern, wenn ein Gesetz klar verfassungswidrig ist.'),
  85: n('The Bundesrat is made of state government members, not separately elected politicians. Change a state government and you change the Bundesrat.',
        'Der Bundesrat besteht aus Mitgliedern der Landesregierungen, nicht aus eigens Gewählten. Ein Regierungswechsel im Land verändert den Bundesrat.'),
  86: n('The Bundesversammlung meets only to elect a president: all Bundestag members plus an equal number chosen by the states.',
        'Die Bundesversammlung tritt nur zur Wahl des Bundespräsidenten zusammen: alle Bundestagsabgeordneten plus ebenso viele von den Ländern.'),
  87: n('Head of state and head of government are two different people here: president and chancellor. Many countries combine them.',
        'Staatsoberhaupt und Regierungschefin sind hier zwei Personen: Bundespräsident und Kanzlerin. Viele Länder legen das zusammen.'),
  88: n('Scrutinising the government is the opposition’s formal job, with rights to ask questions and demand answers in public.',
        'Die Regierung zu kontrollieren ist die formale Aufgabe der Opposition – mit dem Recht, öffentlich zu fragen und Antworten zu verlangen.'),
  89: n('A Fraktion is a party’s group in parliament. Size decides committee seats, speaking time and money, so it matters a great deal.',
        'Eine Fraktion ist die Gruppe einer Partei im Parlament. Ihre Größe entscheidet über Ausschusssitze, Redezeit und Geld.'),
  90: n('The Bundesrat is how the states shape federal law, and for many bills it can block outright.',
        'Über den Bundesrat gestalten die Länder Bundesgesetze mit – bei vielen Vorhaben können sie sie sogar blockieren.'),
  91: n('A state election can change the federal balance, because state governments fill the Bundesrat. This is why national parties campaign hard in state elections.',
        'Eine Landtagswahl kann die Mehrheiten im Bund verschieben, weil Landesregierungen den Bundesrat besetzen. Deshalb kämpfen Bundesparteien dort hart.'),
  92: n('The CSU exists only in Bavaria. The CDU does not stand there, and the two form one group in the Bundestag.',
        'Die CSU gibt es nur in Bayern. Die CDU tritt dort nicht an, und beide bilden im Bundestag eine Fraktion.'),
  93: n('The Zweitstimme decides the size of each party in parliament. It is the more powerful of your two votes.',
        'Die Zweitstimme entscheidet, wie stark eine Partei im Parlament ist. Sie ist die wichtigere deiner beiden Stimmen.'),
  94: n('Eighteen for federal elections. Several states allow sixteen for local and state elections, so check your own state’s rules.',
        'Achtzehn bei Bundestagswahlen. Mehrere Länder erlauben sechzehn bei Kommunal- und Landtagswahlen – prüfe dein Bundesland.'),
  95: n('Children must attend school in person; home schooling is generally not allowed. This surprises families arriving from countries where it is normal.',
        'Kinder müssen wirklich zur Schule gehen; Hausunterricht ist in der Regel nicht erlaubt. Das überrascht Familien aus Ländern, wo es üblich ist.'),
  96: n('Holocaust denial is a criminal offence, not protected speech. Germany draws this line deliberately because of its own history.',
        'Holocaustleugnung ist eine Straftat, keine geschützte Meinung. Deutschland zieht diese Grenze bewusst – wegen der eigenen Geschichte.'),
  97: n('If you are employed, social insurance is automatic. You do not sign up; it appears as deductions on your first payslip.',
        'Als Angestellte bist du automatisch sozialversichert. Du meldest dich nicht an – es steht als Abzug auf der ersten Abrechnung.'),
  98: n('Governments depend on individual MPs. A handful changing group can cost a coalition its majority, which is why party discipline is strong.',
        'Regierungen hängen an einzelnen Abgeordneten. Wechseln ein paar die Fraktion, kann die Mehrheit kippen – deshalb ist der Fraktionszwang stark.'),
  99: n('Employer and employee split the contributions. Your payslip shows your half; your employer pays a similar amount you never see.',
        'Arbeitgeber und Arbeitnehmer teilen sich die Beiträge. Auf deiner Abrechnung steht deine Hälfte; die andere zahlt der Betrieb.'),
  100: n('Life insurance is private and voluntary. The five statutory branches are health, care, pension, unemployment and accident.',
         'Die Lebensversicherung ist privat und freiwillig. Die fünf gesetzlichen Zweige sind Kranken-, Pflege-, Renten-, Arbeitslosen- und Unfallversicherung.'),

  101: n('Unions negotiate the Tarifvertrag that sets pay and hours for whole industries. You benefit from one in many jobs whether or not you are a member.',
         'Gewerkschaften handeln Tarifverträge aus, die Lohn und Arbeitszeit für ganze Branchen festlegen. Davon profitierst du oft, auch ohne Mitglied zu sein.'),
  102: n('The Bundesverdienstkreuz is Germany’s main civilian honour, and it often goes to volunteers rather than to famous people.',
         'Das Bundesverdienstkreuz ist die wichtigste zivile Auszeichnung – oft geht es an Ehrenamtliche, nicht an Prominente.'),
  103: n('Coalitions are nicknamed by their party colours. Ampel is red, yellow and green; learning the colours makes German political news much easier to follow.',
         'Koalitionen heißen nach den Parteifarben. Ampel ist Rot, Gelb, Grün. Wer die Farben kennt, versteht Nachrichten leichter.'),
  104: n('Pregnancy is never a lawful reason for dismissal. Mutterschutz protects you before and after birth, and the protection is strong and automatic.',
         'Schwangerschaft ist nie ein zulässiger Kündigungsgrund. Der Mutterschutz gilt vor und nach der Geburt – stark und automatisch.'),
  105: n('Ordinary volunteers count the votes, in public, in front of anyone who wants to watch. That transparency is why German results are trusted.',
         'Ganz normale Freiwillige zählen die Stimmen – öffentlich, vor allen, die zusehen wollen. Diese Transparenz schafft Vertrauen.'),
  106: n('You can volunteer as a Wahlhelfer yourself once you are a citizen. It is a paid-expenses day and a good way to see democracy up close.',
         'Als Staatsbürgerin kannst du selbst Wahlhelferin werden. Es gibt eine Aufwandsentschädigung – und du siehst Demokratie aus der Nähe.'),
  107: n('Four years between federal elections. That is the rhythm of German national politics.',
         'Vier Jahre zwischen den Bundestagswahlen. Das ist der Takt der Bundespolitik.'),
  108: n('Federal elections are for German citizens only. This is one of the concrete things naturalisation gives you.',
         'Bei Bundestagswahlen dürfen nur deutsche Staatsangehörige wählen. Das ist eines der konkreten Dinge, die die Einbürgerung bringt.'),
  109: n('Every four years, unless parliament dissolves early, which is rare and deliberately hard to do.',
         'Alle vier Jahre – außer bei vorgezogener Auflösung, was selten und bewusst schwierig ist.'),
  110: n('Repeated in the catalogue because it matters: the Bundestag term is four years.',
         'Steht mehrfach im Katalog, weil es wichtig ist: Die Wahlperiode dauert vier Jahre.'),
  111: n('Calling publicly for the destruction of Israel is a crime here. Criticising Israeli government policy is not. Germany draws this line because of the Holocaust.',
         'Der öffentliche Aufruf zur Vernichtung Israels ist strafbar. Kritik an der israelischen Regierungspolitik nicht. Deutschland zieht diese Grenze wegen des Holocaust.'),
  112: n('Secret voting is why the booth has a curtain and why you may not photograph your ballot. Nobody can prove how you voted, so nobody can pressure you.',
         'Geheime Wahl heißt: Vorhang an der Kabine, kein Foto vom Stimmzettel. Niemand kann beweisen, wie du gewählt hast – also dich auch nicht unter Druck setzen.'),
  113: n('Most votes wins, but with several parties that usually means the largest party still has to find coalition partners.',
         'Die meisten Stimmen gewinnen – bei mehreren Parteien heißt das aber meist, dass die stärkste Partei Partner suchen muss.'),
  114: n('Voting is a right here, not a duty. There is no fine for staying home, unlike in Belgium or Australia.',
         'Wählen ist ein Recht, keine Pflicht. Wer zu Hause bleibt, zahlt kein Bußgeld – anders als in Belgien oder Australien.'),
  115: n('Aktiv means you cast a vote; passiv means you can be elected. The words are the opposite way round from what most people guess.',
         'Aktiv heißt: du wählst. Passiv heißt: du kannst gewählt werden. Die Wörter sind anders herum, als die meisten vermuten.'),
  116: n('Being allowed to vote is the aktives Wahlrecht. Expect this pair of terms in several questions.',
         'Wählen dürfen ist das aktive Wahlrecht. Rechne mit diesem Begriffspaar in mehreren Fragen.'),
  117: n('Five percent of Zweitstimmen, or a party gets no seats at all. This single rule shapes every German election campaign.',
         'Fünf Prozent der Zweitstimmen, sonst kein einziger Sitz. Diese eine Regel prägt jeden Wahlkampf.'),
  118: n('Makkabi clubs are Jewish sports clubs open to everyone, of any faith. Sport is one of the most ordinary places integration actually happens.',
         'Makkabi-Vereine sind jüdische Sportvereine, offen für alle – unabhängig vom Glauben. Sport ist einer der Orte, an denen Integration wirklich passiert.'),
  119: n('Free means no pressure from anyone: not your boss, not your family, not a party.',
         'Frei heißt: kein Druck von irgendwem – nicht vom Chef, nicht von der Familie, nicht von einer Partei.'),
  120: n('Germany mixes both systems on one ballot: a person by majority, a party by proportion. That is why you get two votes.',
         'Deutschland mischt beide Systeme auf einem Stimmzettel: eine Person nach Mehrheit, eine Partei nach Verhältnis. Daher die zwei Stimmen.'),
  121: n('The threshold exists so parliament stays governable. Weimar had dozens of tiny parties and no stable majorities.',
         'Die Hürde soll das Parlament regierbar halten. Weimar hatte dutzende Kleinparteien und keine stabilen Mehrheiten.'),
  122: n('Five principles: allgemein, unmittelbar, frei, gleich, geheim. Learning them as a list is the easiest way to remember them.',
         'Fünf Grundsätze: allgemein, unmittelbar, frei, gleich, geheim. Als Liste lernen ist am einfachsten.'),
  123: n('The 5% rule again. It appears in several wordings across the catalogue.',
         'Wieder die Fünf-Prozent-Hürde. Sie kommt im Katalog in mehreren Formulierungen vor.'),
  124: n('A Bundestagswahl elects the national parliament, not a government and not a president.',
         'Die Bundestagswahl wählt das nationale Parlament – keine Regierung und keinen Präsidenten.'),
  125: n('Regular elections mean power is lent, not owned. A government that loses an election simply leaves.',
         'Regelmäßige Wahlen heißen: Macht ist geliehen, nicht besessen. Wer verliert, geht einfach.'),
  126: n('Your Wahlbenachrichtigung arrives by post because you are on the register. It tells you where to vote, and is another reason the Anmeldung matters.',
         'Die Wahlbenachrichtigung kommt per Post, weil du gemeldet bist. Sie sagt, wo du wählst – noch ein Grund, warum die Anmeldung wichtig ist.'),
  127: n('Without the threshold, a parliament of many tiny parties would struggle to form any government at all.',
         'Ohne die Hürde hätte ein Parlament aus vielen Kleinstparteien Mühe, überhaupt eine Regierung zu bilden.'),
  128: n('Abgeordnete are bound only by their conscience, not by instructions from their party. That is in the Grundgesetz.',
         'Abgeordnete sind nur ihrem Gewissen verpflichtet, nicht Weisungen ihrer Partei. Das steht im Grundgesetz.'),
  129: n('Only the Bundestag is elected directly at federal level. Chancellor, president and Bundesrat all come indirectly.',
         'Auf Bundesebene wird nur der Bundestag direkt gewählt. Kanzlerin, Bundespräsident und Bundesrat kommen indirekt zustande.'),
  130: n('One cross per column, nothing written on it. Extra marks or comments make the ballot invalid, so your vote would simply not count.',
         'Ein Kreuz pro Spalte, nichts dazuschreiben. Zusätzliche Zeichen machen den Stimmzettel ungültig – deine Stimme zählt dann nicht.'),
  131: n('The mayor runs your Gemeinde and is usually elected directly by residents, unlike the chancellor.',
         'Die Bürgermeisterin leitet deine Gemeinde und wird meist direkt von den Einwohnern gewählt – anders als die Kanzlerin.'),
  132: n('Ehrenamt means unpaid and voluntary. Fire brigades, sports clubs and refugee support largely run on it, and joining one is a fast way to meet people.',
         'Ehrenamt heißt freiwillig und unbezahlt. Feuerwehren, Sportvereine und Geflüchtetenhilfe leben davon – und es ist ein schneller Weg, Leute kennenzulernen.'),
  133: n('Briefwahl is easy and needs no reason. You request it, the papers come by post, and you send them back before election day.',
         'Briefwahl ist einfach und braucht keine Begründung. Du beantragst sie, bekommst die Unterlagen per Post und schickst sie vor der Wahl zurück.'),
  134: n('Unions represent employees collectively. Individually you have little leverage; together you negotiate the whole industry’s pay.',
         'Gewerkschaften vertreten Beschäftigte gemeinsam. Allein hast du wenig Gewicht, zusammen verhandelt ihr den Lohn einer ganzen Branche.'),
  135: n('Same point, asked again: unions are for employees, not employers. Employers have their own associations.',
         'Derselbe Punkt noch einmal: Gewerkschaften sind für Arbeitnehmerinnen, nicht für Arbeitgeber. Die haben eigene Verbände.'),
  136: n('Employment disputes go to a special Arbeitsgericht, and the first instance is deliberately cheap and quick, without needing a lawyer.',
         'Streit im Job geht ans Arbeitsgericht. Die erste Instanz ist bewusst günstig und schnell – auch ohne Anwältin.'),
  137: n('Germany has separate court branches: labour, social, tax, administrative and ordinary courts. Going to the right one saves months.',
         'Deutschland hat eigene Gerichtszweige: Arbeit, Sozial, Finanz, Verwaltung und ordentliche Gerichte. Der richtige Zweig spart Monate.'),
  138: n('You have three weeks to file a Kündigungsschutzklage. Miss that deadline and the dismissal stands, however unfair it was.',
         'Für die Kündigungsschutzklage hast du drei Wochen. Wer die Frist verpasst, gegen den steht die Kündigung – egal wie unfair sie war.'),
  139: n('A trial happens when the prosecutor brings charges. Being investigated is not the same as being charged, and neither is a conviction.',
         'Zum Prozess kommt es, wenn die Staatsanwaltschaft anklagt. Ermittlung ist nicht Anklage, und Anklage ist nicht Verurteilung.'),
  140: n('Schöffen are ordinary citizens who sit as judges alongside professionals and have an equal vote on guilt. No legal training is required.',
         'Schöffinnen sind normale Bürgerinnen, die neben Berufsrichtern sitzen und bei der Schuldfrage gleichberechtigt mitentscheiden. Juristische Ausbildung braucht es nicht.'),
  141: n('A Rechtsanwalt advises and represents you. If you cannot afford one, Beratungshilfe and Prozesskostenhilfe exist for exactly that.',
         'Eine Rechtsanwältin berät und vertritt dich. Wer sie nicht bezahlen kann, bekommt Beratungshilfe oder Prozesskostenhilfe.'),
  142: n('Judges are independent and effectively cannot be removed or moved for their rulings. That protection is what makes independence real.',
         'Richterinnen sind unabhängig und können für ihre Urteile praktisch nicht versetzt oder entlassen werden. Dieser Schutz macht Unabhängigkeit erst echt.'),
  143: n('Judiciary, one of the three powers. Its whole design is to be separate from the other two.',
         'Judikative, eine der drei Gewalten. Ihr ganzer Aufbau dient dazu, von den anderen getrennt zu sein.'),
  144: n('Rechtsprechende Gewalt is simply the German term for the judiciary. Same thing, different wording.',
         'Rechtsprechende Gewalt ist nur das deutsche Wort für Judikative. Dasselbe, andere Formulierung.'),
  145: n('Again the judiciary. The catalogue tests the three powers from many angles.',
         'Wieder die Judikative. Der Katalog prüft die drei Gewalten aus vielen Blickwinkeln.'),
  146: n('A court case is a Prozess. Most are civil, about money, tenancies or work, not crime.',
         'Ein Gerichtsverfahren heißt Prozess. Die meisten sind zivil: Geld, Miete, Arbeit – nicht Straftaten.'),
  147: n('Judges apply the law to facts. They do not make policy, and they do not take instructions from ministers.',
         'Richterinnen wenden das Gesetz auf Sachverhalte an. Sie machen keine Politik und nehmen keine Weisungen von Ministerinnen.'),
  148: n('Police enforce the law and are bound by it. If you feel wrongly treated, you can complain and take the matter to court.',
         'Die Polizei setzt Gesetze durch und ist an sie gebunden. Wer sich falsch behandelt fühlt, kann sich beschweren und klagen.'),
  149: n('Antisemitism is treated as a serious matter here and can be a criminal offence, not merely bad manners.',
         'Antisemitismus gilt hier als ernste Sache und kann strafbar sein – nicht nur schlechtes Benehmen.'),
  150: n('Schöffen are lay judges, chosen from the public for a fixed term. You could be asked to serve once you are a citizen.',
         'Schöffinnen sind ehrenamtliche Richterinnen, für eine Amtszeit aus der Bevölkerung berufen. Als Staatsbürgerin kannst du gefragt werden.'),
  151: n('The DDR built the Wall, to stop its own people leaving. It was officially called an anti-fascist protection barrier, which it was not.',
         'Die Mauer baute die DDR, um die eigene Bevölkerung am Weggehen zu hindern. Offiziell hieß sie antifaschistischer Schutzwall – das war sie nicht.'),
  152: n('Twelve years, 1933 to 1945. Almost every rule in the Grundgesetz is a response to them.',
         'Zwölf Jahre, 1933 bis 1945. Fast jede Regel im Grundgesetz ist eine Antwort darauf.'),
  153: n('8 May 1945 is remembered here as liberation, not only defeat. It is a public day of remembrance.',
         'Der 8. Mai 1945 gilt hier als Befreiung, nicht nur als Niederlage. Er ist ein Gedenktag.'),
  154: n('1945. The war Germany began ended with its unconditional surrender and the country in ruins and occupied.',
         '1945. Der von Deutschland begonnene Krieg endete mit der bedingungslosen Kapitulation, das Land zerstört und besetzt.'),
  155: n('The same twelve years, asked again. 1933 to 1945 is worth memorising as a single fact.',
         'Dieselben zwölf Jahre, noch einmal gefragt. 1933 bis 1945 lohnt sich als eine Zahl zu merken.'),
  156: n('Hitler was appointed chancellor legally in January 1933, then dismantled democracy from inside it within months.',
         'Hitler wurde im Januar 1933 legal zum Reichskanzler ernannt und baute die Demokratie dann binnen Monaten von innen ab.'),
  157: n('A dictatorship, established through legal-looking steps. That is precisely why the Grundgesetz makes some things unchangeable.',
         'Eine Diktatur, errichtet über scheinbar legale Schritte. Genau deshalb macht das Grundgesetz manches unveränderbar.'),
  158: n('The term Drittes Reich was Nazi propaganda. Historians and this exam use it in quotation marks.',
         'Der Begriff „Drittes Reich" war NS-Propaganda. Historiker und dieser Test setzen ihn in Anführungszeichen.'),
  159: n('No free elections, no free press, no opposition, no independent courts. All four are guaranteed today for that reason.',
         'Keine freien Wahlen, keine freie Presse, keine Opposition, keine unabhängigen Gerichte. Alle vier sind heute genau deshalb garantiert.'),
  160: n('1939 to 1945, started by Germany with the invasion of Poland.',
         '1939 bis 1945, begonnen von Deutschland mit dem Überfall auf Polen.'),
  161: n('State racism was the organising principle, not a side effect. It led directly to the Holocaust.',
         'Staatlicher Rassismus war das Ordnungsprinzip, nicht ein Nebeneffekt. Er führte direkt zum Holocaust.'),
  162: n('Stauffenberg’s 20 July 1944 attempt failed and he was shot. German resistance existed, and is honoured, though it was a minority.',
         'Stauffenbergs Attentat vom 20. Juli 1944 scheiterte, er wurde erschossen. Deutschen Widerstand gab es – er wird geehrt, war aber eine Minderheit.'),
  163: n('1938. You may see brass Stolpersteine in pavements outside houses where deported Jewish neighbours once lived.',
         '1938. In Gehwegen siehst du messingfarbene Stolpersteine vor Häusern, in denen deportierte jüdische Nachbarn lebten.'),
  164: n('The November pogroms of 1938: synagogues burned, shops destroyed, people murdered, while the state organised it and the police stood by.',
         'Die Novemberpogrome 1938: brennende Synagogen, zerstörte Geschäfte, Ermordete – organisiert vom Staat, während die Polizei zusah.'),
  165: n('Konrad Adenauer, chancellor from 1949, tied West Germany firmly to the West and to European integration.',
         'Konrad Adenauer, Kanzler ab 1949, band die Bundesrepublik fest an den Westen und die europäische Einigung.'),
  166: n('"Wir sind das Volk" was chanted at the Leipzig Monday demonstrations in 1989. The protests stayed peaceful and the state gave way.',
         '„Wir sind das Volk" riefen die Leipziger Montagsdemonstrationen 1989. Die Proteste blieben friedlich, und der Staat gab nach.'),
  167: n('Four occupying powers: USA, Soviet Union, Britain, France. Their four zones became two German states.',
         'Vier Besatzungsmächte: USA, Sowjetunion, Großbritannien, Frankreich. Aus ihren vier Zonen wurden zwei deutsche Staaten.'),
  168: n('Japan was Germany’s ally in the war, not an occupier of it.',
         'Japan war im Krieg Deutschlands Verbündeter, keine Besatzungsmacht.'),
  169: n('1949: the Grundgesetz came into force in May, and the Bundesrepublik began.',
         '1949: Im Mai trat das Grundgesetz in Kraft, die Bundesrepublik begann.'),
  170: n('All parties but the NSDAP were banned in 1933. That is why banning anti-democratic parties today is left strictly to the courts.',
         '1933 wurden alle Parteien außer der NSDAP verboten. Deshalb dürfen heute nur Gerichte über Parteiverbote entscheiden.'),
  171: n('Supply and demand set prices, but the state sets limits: worker protection, competition law and social insurance.',
         'Angebot und Nachfrage bestimmen die Preise, aber der Staat setzt Grenzen: Arbeitsschutz, Wettbewerbsrecht, Sozialversicherung.'),
  172: n('The DDR was founded in the Soviet zone in October 1949, months after the Bundesrepublik in the west.',
         'Die DDR entstand im Oktober 1949 in der sowjetischen Zone, Monate nach der Bundesrepublik im Westen.'),
  173: n('Germany helped found the European project from the start, deliberately binding itself to its neighbours after the war.',
         'Deutschland gehörte von Anfang an zu den Gründern des europäischen Projekts – bewusste Bindung an die Nachbarn nach dem Krieg.'),
  174: n('Both German states were founded in 1949, only months apart.',
         'Beide deutschen Staaten entstanden 1949, nur wenige Monate auseinander.'),
  175: n('Four zones. Berlin, deep inside the Soviet zone, was itself split into four sectors.',
         'Vier Zonen. Berlin lag mitten in der sowjetischen Zone und wurde selbst in vier Sektoren geteilt.'),
  176: n('The map is worth memorising: British north, Soviet east, American south, French south-west.',
         'Die Karte lohnt sich zu merken: Briten im Norden, Sowjets im Osten, USA im Süden, Frankreich im Südwesten.'),
  177: n('Berlin was divided into four sectors although it lay inside the Soviet zone, which is why the city became the front line of the Cold War.',
         'Berlin wurde in vier Sektoren geteilt, obwohl es in der sowjetischen Zone lag. Deshalb wurde die Stadt zur Front des Kalten Krieges.'),
  178: n('During the 1948 blockade, West Berlin was supplied entirely by air for almost a year. Berliners called the planes Rosinenbomber.',
         'Während der Blockade 1948 wurde West-Berlin fast ein Jahr lang nur aus der Luft versorgt. Die Berliner nannten die Flugzeuge Rosinenbomber.'),
  179: n('Unconditional surrender, signed in May 1945. There were no negotiated terms.',
         'Bedingungslose Kapitulation, unterzeichnet im Mai 1945. Verhandelte Bedingungen gab es nicht.'),
  180: n('Adenauer again, the catalogue asks twice. He governed for fourteen years.',
         'Wieder Adenauer, der Katalog fragt zweimal. Er regierte vierzehn Jahre.'),
  181: n('Brandt knelt unannounced at the Warsaw Ghetto memorial in 1970. The gesture said what a speech could not, and is still taught in schools.',
         'Brandt kniete 1970 unangekündigt am Mahnmal des Warschauer Ghettos. Die Geste sagte, was keine Rede konnte – sie wird bis heute in Schulen behandelt.'),
  182: n('A synagogue is a Jewish house of prayer. Many German ones are still guarded by police, which says something about the present.',
         'Eine Synagoge ist ein jüdisches Gebetshaus. Viele werden in Deutschland weiterhin polizeilich geschützt – das sagt etwas über die Gegenwart.'),
  183: n('The 1950s boom rebuilt West Germany and brought in millions of guest workers, whose families are a large part of Germany today.',
         'Der Boom der 50er Jahre baute die Bundesrepublik wieder auf und holte Millionen Gastarbeiter – deren Familien heute ein großer Teil Deutschlands sind.'),
  184: n('The United Nations, in 1947. Germany’s particular responsibility towards Israel comes from the Holocaust, but it did not yet exist as a state in 1948.',
         'Die Vereinten Nationen, 1947. Deutschlands besondere Verantwortung gegenüber Israel folgt aus dem Holocaust – als Staat existierte es 1948 aber noch nicht.'),
  185: n('The Iron Curtain sealed the eastern bloc off from the west. For forty years it ran straight through Germany.',
         'Der Eiserne Vorhang schottete den Ostblock vom Westen ab. Vierzig Jahre lang verlief er mitten durch Deutschland.'),
  186: n('The 17 June 1953 uprising was crushed by Soviet tanks. West Germany kept the date as its national holiday until 1990.',
         'Der Aufstand vom 17. Juni 1953 wurde von sowjetischen Panzern niedergeschlagen. Bis 1990 war der Tag der westdeutsche Nationalfeiertag.'),
  187: n('Same three colours, different emblem. Hammer, compass and rye ring marked the DDR flag.',
         'Dieselben drei Farben, anderes Emblem. Hammer, Zirkel und Ährenkranz kennzeichneten die DDR-Flagge.'),
  188: n('1961, built almost overnight in August. Families woke up on opposite sides of it.',
         '1961, im August fast über Nacht gebaut. Familien wachten auf verschiedenen Seiten auf.'),
  189: n('The DDR built it, in 1961. Both facts are asked separately in the catalogue.',
         'Die DDR baute sie, 1961. Beide Fakten werden im Katalog getrennt gefragt.'),
  190: n('Deutsche Demokratische Republik. The name said democratic; the reality was a one-party state.',
         'Deutsche Demokratische Republik. Der Name sagte demokratisch, die Wirklichkeit war ein Einparteienstaat.'),
  191: n('9 November 1989, opened by a confused press conference and a crowd that simply walked through. Nobody fired a shot.',
         'Am 9. November 1989 – ausgelöst durch eine verwirrte Pressekonferenz und eine Menge, die einfach durchging. Niemand schoss.'),
  192: n('Brandenburg surrounds Berlin and was part of the DDR. Five states joined the Bundesrepublik in 1990.',
         'Brandenburg umschließt Berlin und gehörte zur DDR. 1990 traten fünf Länder der Bundesrepublik bei.'),
  193: n('Twenty-eight years of division. People alive today grew up unable to visit relatives a few streets away.',
         'Achtundzwanzig Jahre Teilung. Menschen, die heute leben, konnten Verwandte ein paar Straßen weiter nicht besuchen.'),
  194: n('3 October is the national holiday, marking unification in 1990 rather than any battle or revolution.',
         'Der 3. Oktober ist der Nationalfeiertag – für die Vereinigung 1990, nicht für eine Schlacht oder Revolution.'),
  195: n('Sachsen-Anhalt was one of the five new states. Its ten state questions are in this app if you live there.',
         'Sachsen-Anhalt war eines der fünf neuen Länder. Seine zehn Landesfragen sind in dieser App, wenn du dort wohnst.'),
  196: n('Die Wende means the turn from dictatorship to democracy, driven by ordinary people in the streets.',
         'Die Wende meint den Übergang von der Diktatur zur Demokratie, getragen von normalen Menschen auf der Straße.'),
  197: n('Thüringen, another of the five states that joined in 1990.',
         'Thüringen, ein weiteres der fünf Länder, die 1990 beitraten.'),
  198: n('Sachsen, where the Leipzig Monday demonstrations began.',
         'Sachsen, wo die Leipziger Montagsdemonstrationen begannen.'),
  199: n('The Stasi kept files on millions and used ordinary neighbours as informants. You can still apply to read your own file.',
         'Die Stasi führte Akten über Millionen und nutzte Nachbarn als Spitzel. Die eigene Akte kann man bis heute einsehen.'),
  200: n('Mecklenburg-Vorpommern, the fifth of the new states, on the Baltic coast.',
         'Mecklenburg-Vorpommern, das fünfte neue Land, an der Ostsee.'),

  201: n('The five new states: Mecklenburg-Vorpommern, Brandenburg, Sachsen-Anhalt, Sachsen and Thüringen, plus East Berlin.',
         'Die fünf neuen Länder: Mecklenburg-Vorpommern, Brandenburg, Sachsen-Anhalt, Sachsen und Thüringen, dazu Ost-Berlin.'),
  202: n('The DDR belonged to the Warsaw Pact, the Soviet answer to NATO. Germany had one state in each bloc.',
         'Die DDR gehörte zum Warschauer Pakt, der sowjetischen Antwort auf die NATO. Deutschland hatte in jedem Block einen Staat.'),
  203: n('A planned economy set prices and output centrally. Shortages and years-long waiting lists for a car were normal.',
         'Die Planwirtschaft legte Preise und Produktion zentral fest. Mangel und jahrelange Wartezeiten auf ein Auto waren normal.'),
  204: n('The DDR joined the Bundesrepublik rather than the two merging into something new, which is why the Grundgesetz simply continued.',
         'Die DDR trat der Bundesrepublik bei, statt dass beide zu etwas Neuem verschmolzen. Deshalb galt das Grundgesetz einfach weiter.'),
  205: n('The new states joined the EU automatically in 1990, without any separate accession process.',
         'Die neuen Länder kamen 1990 automatisch in die EU, ohne eigenes Beitrittsverfahren.'),
  206: n('Stolpersteine are small brass plaques in the pavement outside the last freely chosen home of someone murdered by the Nazis. There are tens of thousands.',
         'Stolpersteine sind kleine Messingtafeln im Gehweg vor der letzten frei gewählten Wohnung eines NS-Opfers. Es gibt zehntausende.'),
  207: n('The Warsaw Pact again, asked from the military angle.',
         'Wieder der Warschauer Pakt, hier aus militärischer Sicht gefragt.'),
  208: n('The Stasi was the DDR secret police, with files on millions and a vast network of unofficial informants.',
         'Die Stasi war der Geheimdienst der DDR – mit Akten über Millionen und einem riesigen Netz inoffizieller Mitarbeiter.'),
  209: n('Hammer, compass and rye ring: workers, intelligentsia and farmers. The symbol tells you what the state claimed to be.',
         'Hammer, Zirkel, Ährenkranz: Arbeiter, Intelligenz, Bauern. Das Symbol sagt, was der Staat zu sein behauptete.'),
  210: n('Workers struck across the DDR in June 1953 and Soviet tanks ended it. It was a workers’ uprising against a workers’ state.',
         'Im Juni 1953 streikten Arbeiter in der ganzen DDR, sowjetische Panzer beendeten es. Ein Arbeiteraufstand gegen einen Arbeiterstaat.'),
  211: n('Brandt’s Ostpolitik sought reconciliation with the east. It was bitterly controversial at home and won him the Nobel Peace Prize.',
         'Brandts Ostpolitik suchte Versöhnung mit dem Osten. Zu Hause war sie heftig umstritten, ihm brachte sie den Friedensnobelpreis.'),
  212: n('The full name is Bundesrepublik Deutschland. Bundes- signals the federal structure right there in the name.',
         'Der volle Name ist Bundesrepublik Deutschland. Das „Bundes" zeigt schon im Namen den föderalen Aufbau.'),
  213: n('Around 84 million people, the largest population in the EU.',
         'Etwa 84 Millionen Menschen – die größte Bevölkerung in der EU.'),
  214: n('Black, red, gold. The colours come from the 1848 democratic movement, not from any monarchy.',
         'Schwarz-Rot-Gold. Die Farben stammen aus der demokratischen Bewegung von 1848, nicht von einer Monarchie.'),
  215: n('Helmut Kohl pushed reunification through quickly in 1989 and 1990, against considerable international caution.',
         'Helmut Kohl trieb die Wiedervereinigung 1989/90 rasch voran – gegen erhebliche internationale Zurückhaltung.'),
  216: n('A large stylised eagle hangs over the Bundestag chamber. Members nicknamed it die fette Henne, the fat hen.',
         'Über dem Plenarsaal hängt ein großer stilisierter Adler. Abgeordnete nennen ihn „die fette Henne".'),
  217: n('The DDR existed for 41 years, 1949 to 1990. Many people alive today spent their whole childhood in it.',
         'Die DDR bestand 41 Jahre, 1949 bis 1990. Viele Menschen heute verbrachten ihre ganze Kindheit dort.'),
  218: n('Five states joined in 1990, taking the total from eleven to sixteen.',
         '1990 kamen fünf Länder dazu, von elf auf sechzehn.'),
  219: n('Germany’s borders have been settled since 1990, confirmed by treaty with its neighbours.',
         'Seit 1990 stehen Deutschlands Grenzen fest, vertraglich mit den Nachbarn bestätigt.'),
  220: n('27 January is the day Auschwitz was liberated. Remembrance is a public duty here, not a private matter.',
         'Am 27. Januar wurde Auschwitz befreit. Erinnern ist hier öffentliche Aufgabe, nicht Privatsache.'),
  221: n('Schengen is why you can drive to the Netherlands or Austria without stopping at a border post.',
         'Schengen ist der Grund, warum du ohne Grenzposten in die Niederlande oder nach Österreich fahren kannst.'),
  222: n('Germany has nine neighbours, more than almost any country in Europe. Switzerland is one of them.',
         'Deutschland hat neun Nachbarn, mehr als fast jedes Land in Europa. Die Schweiz ist einer davon.'),
  223: n('Poland lies to the east. The border has been recognised by treaty since reunification.',
         'Polen liegt im Osten. Die Grenze ist seit der Wiedervereinigung vertraglich anerkannt.'),
  224: n('EU is Europäische Union. Learning the nine neighbours as a list is the quickest way to handle this whole question group.',
         'EU heißt Europäische Union. Die neun Nachbarn als Liste zu lernen erledigt diese ganze Fragengruppe am schnellsten.'),
  225: n('German is the official language of Austria, and of Liechtenstein, and one of several in Switzerland and Belgium.',
         'Deutsch ist Amtssprache in Österreich und Liechtenstein und eine von mehreren in der Schweiz und Belgien.'),
  226: n('Twelve gold stars on blue. The number is fixed at twelve and has nothing to do with how many members there are.',
         'Zwölf goldene Sterne auf Blau. Die Zahl ist fest und hat nichts mit der Zahl der Mitglieder zu tun.'),
  227: n('Denmark is the northern neighbour, across the only land border Germany has to the north.',
         'Dänemark ist der nördliche Nachbar – die einzige Landgrenze Deutschlands nach Norden.'),
  228: n('Deutsche Wiedervereinigung, marked every 3 October.',
         'Deutsche Wiedervereinigung, gefeiert jedes Jahr am 3. Oktober.'),
  229: n('Luxembourg is the smallest of the nine neighbours, and many people commute across that border daily for work.',
         'Luxemburg ist der kleinste der neun Nachbarn. Viele pendeln täglich über diese Grenze zur Arbeit.'),
  230: n('The European Parliament is elected every five years, and EU citizens can vote in it from their country of residence.',
         'Das Europäische Parlament wird alle fünf Jahre gewählt. EU-Bürgerinnen können dort auch vom Wohnsitzland aus wählen.'),
  231: n('European integration means tying countries together so closely that war between them becomes impractical. That was the founding motive.',
         'Europäische Integration heißt: Länder so eng verbinden, dass Krieg zwischen ihnen unpraktikabel wird. Das war das Gründungsmotiv.'),
  232: n('You elect members of the European Parliament directly. It is the only directly elected EU institution.',
         'Du wählst die Abgeordneten des Europäischen Parlaments direkt. Es ist die einzige direkt gewählte EU-Institution.'),
  233: n('Czechia borders Bavaria and Saxony to the south-east.',
         'Tschechien grenzt im Südosten an Bayern und Sachsen.'),
  234: n('Strasbourg is the official seat, a deliberate symbol: a city fought over by France and Germany for centuries.',
         'Straßburg ist der offizielle Sitz – ein bewusstes Symbol: eine Stadt, um die Frankreich und Deutschland jahrhundertelang kämpften.'),
  235: n('Mitterrand and Kohl held hands at Verdun in 1984, where hundreds of thousands had died. The image became the symbol of reconciliation.',
         'Mitterrand und Kohl hielten sich 1984 in Verdun an den Händen, wo Hunderttausende gefallen waren. Das Bild wurde zum Symbol der Versöhnung.'),
  236: n('27 member states since the United Kingdom left in 2020.',
         '27 Mitgliedstaaten, seit das Vereinigte Königreich 2020 ausgetreten ist.'),
  237: n('The 1957 Treaties of Rome created the EEC, the common market that grew into today’s EU.',
         'Die Römischen Verträge von 1957 schufen die EWG, den gemeinsamen Markt, aus dem die heutige EU wurde.'),
  238: n('Three cities: Strasbourg for plenary sessions, Brussels for committees, Luxembourg for administration.',
         'Drei Städte: Straßburg für Plenarsitzungen, Brüssel für Ausschüsse, Luxemburg für die Verwaltung.'),
  239: n('The Treaties of Rome again. This pair of questions is asked from two directions.',
         'Wieder die Römischen Verträge. Dieses Fragenpaar kommt aus zwei Richtungen.'),
  240: n('Euro notes and coins arrived in 2002. Older people still occasionally convert prices into D-Mark in their heads.',
         'Euro-Scheine und -Münzen kamen 2002. Ältere rechnen Preise manchmal noch im Kopf in D-Mark um.'),
  241: n('Elterngeld must be applied for at the Elterngeldstelle. Nothing arrives automatically; German benefits nearly always need an Antrag.',
         'Elterngeld musst du bei der Elterngeldstelle beantragen. Nichts kommt automatisch – deutsche Leistungen brauchen fast immer einen Antrag.'),
  242: n('Kindergarten is a parental choice, not compulsory, but children from three have a legal right to a place.',
         'Der Kindergarten ist Elternentscheidung, keine Pflicht – ab drei Jahren gibt es aber einen Rechtsanspruch auf einen Platz.'),
  243: n('You notify a demonstration, you do not ask permission. Assembly is a basic right, and the authority can only impose conditions.',
         'Eine Demonstration meldest du an, du bittest nicht um Erlaubnis. Versammlung ist ein Grundrecht; die Behörde kann nur Auflagen machen.'),
  244: n('The Abitur is the standard route to university, but not the only one: vocational qualifications and Fachhochschulreife also open doors.',
         'Das Abitur ist der Standardweg zur Universität, aber nicht der einzige: Auch berufliche Abschlüsse und die Fachhochschulreife öffnen Türen.'),
  245: n('Adults may not have a relationship with a 13-year-old. Child protection law is strict and is enforced.',
         'Erwachsene dürfen keine Beziehung zu einer 13-Jährigen haben. Der Kinderschutz ist streng und wird durchgesetzt.'),
  246: n('Eighteen. At that point you can sign contracts, vote and are fully responsible for yourself.',
         'Mit achtzehn. Ab dann kannst du Verträge schließen, wählen und bist voll selbst verantwortlich.'),
  247: n('Mutterschutz bans work shortly before and after birth while pay continues. It is automatic, not something you negotiate.',
         'Der Mutterschutz verbietet Arbeit kurz vor und nach der Geburt, das Geld läuft weiter. Er gilt automatisch, nicht auf Verhandlung.'),
  248: n('Raising children is the parents’ right and duty. The state only steps in when a child is at risk.',
         'Kindererziehung ist Recht und Pflicht der Eltern. Der Staat greift nur ein, wenn ein Kind gefährdet ist.'),
  249: n('Asked twice: parents are primarily responsible, with the state as a backstop rather than a manager.',
         'Zweimal gefragt: Eltern sind hauptverantwortlich, der Staat ist Auffangnetz, nicht Aufseher.'),
  250: n('Qualifications matter a lot here, and it is normal to retrain in mid-career. Foreign qualifications can often be formally recognised.',
         'Abschlüsse zählen hier viel, und Umschulung mitten im Berufsleben ist normal. Ausländische Abschlüsse lassen sich oft anerkennen.'),
  251: n('Hitting children is a criminal offence. Children have a legal right to a non-violent upbringing, and this often surprises new arrivals.',
         'Kinder zu schlagen ist strafbar. Kinder haben ein Recht auf gewaltfreie Erziehung – das überrascht viele Neuangekommene.'),
  252: n('One spouse at a time. A second marriage while the first stands is void and a criminal offence.',
         'Nur eine Ehe gleichzeitig. Eine zweite Heirat bei bestehender Ehe ist nichtig und strafbar.'),
  253: n('Within 14 days of moving, at the Einwohnermeldeamt or Bürgeramt. This one appointment unlocks your tax ID, bank account and much else.',
         'Binnen 14 Tagen nach dem Umzug beim Einwohnermelde- oder Bürgeramt. Dieser eine Termin schaltet Steuer-ID, Bankkonto und vieles frei.'),
  254: n('Normally a year of living apart before divorce. The waiting period exists to make sure the decision is settled.',
         'Normalerweise ein Trennungsjahr vor der Scheidung. Die Wartezeit soll sicherstellen, dass die Entscheidung feststeht.'),
  255: n('The Jugendamt is there to support families, not only to intervene. Asking it for help early is normal and sensible.',
         'Das Jugendamt unterstützt Familien, es greift nicht nur ein. Früh um Hilfe zu bitten ist normal und sinnvoll.'),
  256: n('Many trades need a licence. Restaurants need a Gaststättenerlaubnis, and opening without one is an offence.',
         'Viele Gewerbe brauchen eine Erlaubnis. Für ein Restaurant ist es die Gaststättenerlaubnis – ohne sie zu öffnen ist eine Ordnungswidrigkeit.'),
  257: n('Adults can take the Abitur at an Abendgymnasium alongside a job. Education here has second and third chances built in.',
         'Erwachsene können das Abitur am Abendgymnasium neben dem Beruf nachholen. Das Bildungssystem hat zweite und dritte Chancen eingebaut.'),
  258: n('The Jugendamt can remove a child in danger, but only under strict rules and with court oversight.',
         'Das Jugendamt kann ein gefährdetes Kind herausnehmen – aber nur nach strengen Regeln und unter gerichtlicher Kontrolle.'),
  259: n('The BIZ is free and open to anyone. It helps with apprenticeships, career changes and aptitude tests.',
         'Das BIZ ist kostenlos und für alle offen. Es hilft bei Lehrstellen, Berufswechsel und Eignungstests.'),
  260: n('Children must physically attend. Unexcused absence brings letters, then fines, then a visit.',
         'Kinder müssen wirklich da sein. Unentschuldigtes Fehlen bringt erst Briefe, dann Bußgelder, dann Besuch.'),
  261: n('Abendgymnasium again. The catalogue asks it twice because second-chance education matters.',
         'Wieder das Abendgymnasium. Der Katalog fragt zweimal, weil der zweite Bildungsweg wichtig ist.'),
  262: n('Equal treatment covers disability, origin, sex, age, religion and sexual orientation. The AGG lets you act on a breach.',
         'Gleichbehandlung gilt für Behinderung, Herkunft, Geschlecht, Alter, Religion und sexuelle Orientierung. Das AGG gibt dir Mittel dagegen.'),
  263: n('Criminal responsibility starts at 14, and juvenile law focuses on education rather than punishment until 21.',
         'Strafmündig ist man ab 14. Das Jugendstrafrecht setzt bis 21 auf Erziehung statt auf Strafe.'),
  264: n('Karneval or Fasching, biggest in Cologne, Düsseldorf and Mainz. Rosenmontag is the peak and a de facto holiday there.',
         'Karneval oder Fasching, am größten in Köln, Düsseldorf und Mainz. Rosenmontag ist der Höhepunkt und dort faktisch frei.'),
  265: n('Only a Standesamt marriage is legally valid. A religious ceremony is optional and has no legal effect on its own.',
         'Rechtlich gültig ist nur die Ehe auf dem Standesamt. Eine religiöse Feier ist freiwillig und allein ohne Rechtswirkung.'),
  266: n('Quiet hours usually start at 22:00, and all day Sunday. Neighbours do enforce this, and repeated noise can cost you your flat.',
         'Die Nachtruhe beginnt meist um 22 Uhr, dazu der ganze Sonntag. Nachbarn setzen das durch, und Dauerlärm kann die Wohnung kosten.'),
  267: n('Adults decide for themselves. Parents have no say over an adult child’s relationship, even if they disapprove.',
         'Volljährige entscheiden selbst. Eltern haben bei der Beziehung eines erwachsenen Kindes nichts zu bestimmen, auch wenn es ihnen nicht passt.'),
  268: n('The theory test is available in several languages and can be taken orally. Ask the driving school, the options exist.',
         'Die Theorieprüfung gibt es in mehreren Sprachen und auch mündlich. Frag die Fahrschule – die Möglichkeiten bestehen.'),
  269: n('Children from three have a legal right to a Kindergarten place, though in practice you often have to queue for one.',
         'Ab drei Jahren gibt es einen Rechtsanspruch auf einen Kindergartenplatz – in der Praxis muss man sich trotzdem oft anstellen.'),
  270: n('The Volkshochschule is the cheapest adult education there is: German courses, computing, cooking, in almost every town.',
         'Die Volkshochschule ist die günstigste Erwachsenenbildung: Deutschkurse, EDV, Kochen – in fast jeder Stadt.'),
  271: n('The tree, and Christmas Eve rather than Christmas morning: in Germany the presents come on 24 December.',
         'Der Tannenbaum – und der Heiligabend statt des Morgens: In Deutschland gibt es die Geschenke am 24. Dezember.'),
  272: n('Polygamy is not recognised and not permitted, regardless of where a marriage was contracted.',
         'Mehrehe ist weder anerkannt noch erlaubt, unabhängig davon, wo geheiratet wurde.'),
  273: n('The Jugendamt again. It is the standard address for family difficulties.',
         'Wieder das Jugendamt. Es ist die Standardadresse bei Problemen in der Familie.'),
  274: n('Opening someone else’s post is a crime. The Briefgeheimnis is a basic right in Article 10.',
         'Fremde Post zu öffnen ist strafbar. Das Briefgeheimnis ist ein Grundrecht in Artikel 10.'),
  275: n('Divorce requires a lawyer and a court. There is no purely administrative divorce in Germany.',
         'Für eine Scheidung brauchst du Anwältin und Gericht. Eine rein behördliche Scheidung gibt es in Deutschland nicht.'),
  276: n('If an official treats you badly, complain up the chain. Authorities have complaint procedures and are obliged to answer.',
         'Wenn dich jemand im Amt schlecht behandelt, beschwere dich bei der Leitung. Behörden haben Beschwerdewege und müssen antworten.'),
  277: n('Being a mother is not a lawful reason to reject an applicant. That is direct discrimination under the AGG.',
         'Mutter zu sein ist kein zulässiger Ablehnungsgrund. Das ist unmittelbare Diskriminierung nach dem AGG.'),
  278: n('A wheelchair is irrelevant to bookkeeping. Employers must also make reasonable adjustments.',
         'Ein Rollstuhl hat mit Buchhaltung nichts zu tun. Arbeitgeber müssen zudem angemessene Vorkehrungen treffen.'),
  279: n('The Hausordnung binds everyone in the building: quiet hours, bins, stairwell cleaning. Read it when you move in.',
         'Die Hausordnung gilt für alle im Haus: Ruhezeiten, Mülltonnen, Treppenhausreinigung. Lies sie beim Einzug.'),
  280: n('Against a tax assessment you file an Einspruch, normally within one month. The deadline is short and strict.',
         'Gegen einen Steuerbescheid legst du Einspruch ein, meist binnen eines Monats. Die Frist ist kurz und strikt.'),
  281: n('Everyone gets in on the same terms. Refusing someone entry over their origin is illegal.',
         'Alle kommen zu denselben Bedingungen hinein. Jemanden wegen der Herkunft abzuweisen ist rechtswidrig.'),
  282: n('Serving as a Wahlhelfer is one of the few duties citizens can actually be required to take on.',
         'Wahlhelferin zu sein ist eine der wenigen Pflichten, zu denen Bürgerinnen wirklich herangezogen werden können.'),
  283: n('Against an authority’s decision you file a Widerspruch. Do it in writing and keep proof of the date.',
         'Gegen eine Behördenentscheidung legst du Widerspruch ein. Schriftlich, und bewahre einen Nachweis des Datums auf.'),
  284: n('Lifelong learning is expected here. Employers and the Agentur für Arbeit both fund retraining.',
         'Lebenslanges Lernen wird hier erwartet. Arbeitgeber und Agentur für Arbeit finanzieren Weiterbildung.'),
  285: n('Employees do not pay Umsatzsteuer on their wages; that is a tax on business sales. Your payslip shows Lohnsteuer instead.',
         'Angestellte zahlen auf den Lohn keine Umsatzsteuer – die betrifft Unternehmensumsätze. Auf der Abrechnung steht Lohnsteuer.'),
  286: n('The Betriebsrat is elected by the workforce and has legal rights over hours, shifts and dismissals.',
         'Der Betriebsrat wird von der Belegschaft gewählt und hat Rechte bei Arbeitszeit, Schichten und Kündigungen.'),
  287: n('Notice periods bind both sides. Check your contract before resigning, because leaving early can cost you.',
         'Kündigungsfristen gelten für beide Seiten. Prüfe den Vertrag vor der Kündigung – zu früh gehen kann teuer werden.'),
  288: n('Germany’s responsibility towards Israel follows directly from the Holocaust. It is treated as a permanent obligation, not a policy of the day.',
         'Deutschlands Verantwortung gegenüber Israel folgt direkt aus dem Holocaust. Sie gilt als dauerhafte Verpflichtung, nicht als Tagespolitik.'),
  289: n('Skin colour is never a lawful reason to reject an applicant, whatever a customer might prefer.',
         'Hautfarbe ist nie ein zulässiger Ablehnungsgrund – egal, was Gäste angeblich bevorzugen.'),
  290: n('Faulty goods can be returned to the seller, not the manufacturer. You have two years of statutory warranty.',
         'Mangelhafte Ware reklamierst du beim Verkäufer, nicht beim Hersteller. Es gilt zwei Jahre Gewährleistung.'),
  291: n('The tax office collects church tax for registered members. If you name a church when registering, the tax starts.',
         'Das Finanzamt zieht die Kirchensteuer für Mitglieder ein. Wer bei der Anmeldung eine Kirche angibt, zahlt sie.'),
  292: n('Religious tolerance means others may believe what you do not. It protects your belief precisely by protecting theirs.',
         'Religiöse Toleranz heißt: Andere dürfen glauben, was du nicht glaubst. Sie schützt deinen Glauben, indem sie ihren schützt.'),
  293: n('Painted eggs and egg hunts. Good Friday and Easter Monday are both public holidays across Germany.',
         'Bemalte Eier und Eiersuche. Karfreitag und Ostermontag sind bundesweit Feiertage.'),
  294: n('Pentecost is Christian, and Whit Monday is a public holiday. Several German holidays are religious in origin even for non-religious people.',
         'Pfingsten ist christlich, der Pfingstmontag ist Feiertag. Mehrere deutsche Feiertage sind religiösen Ursprungs, auch für Nichtgläubige.'),
  295: n('Christianity shaped the calendar, the holidays and much of the law, which is a historical fact rather than a requirement to believe.',
         'Das Christentum prägte Kalender, Feiertage und viel Recht. Das ist eine historische Tatsache, keine Glaubenspflicht.'),
  296: n('Advent, the four weeks before Christmas, with a wreath, calendars and markets in almost every town.',
         'Die Adventszeit, die vier Wochen vor Weihnachten – mit Kranz, Kalender und Märkten in fast jeder Stadt.'),
  297: n('Turkey. Families who came as guest workers from the 1960s are now in their third and fourth German-born generation.',
         'Die Türkei. Familien, die ab den 1960ern als Gastarbeiter kamen, sind heute in der dritten und vierten hier geborenen Generation.'),
  298: n('The DDR brought in workers from allied socialist states, chiefly Vietnam, Poland and Mozambique.',
         'Die DDR holte Arbeitskräfte aus befreundeten sozialistischen Staaten, vor allem Vietnam, Polen und Mosambik.'),
  299: n('They were called Gastarbeiter, guests who were expected to leave. Most stayed, and Germany took decades to accept that it had become a country of immigration.',
         'Sie hießen Gastarbeiter – Gäste, die wieder gehen sollten. Die meisten blieben, und Deutschland brauchte Jahrzehnte, um sich als Einwanderungsland zu sehen.'),
  300: n('Italy signed the first recruitment agreement, in 1955. Spain, Greece, Turkey and others followed.',
         'Italien schloss 1955 das erste Anwerbeabkommen. Spanien, Griechenland, die Türkei und andere folgten.'),
};
